require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HouseholdsController do

  # This should return the minimal set of attributes required to create a valid
  # Household. As you add validations to Household, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HouseholdsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all households as @households" do
      household = Household.create! valid_attributes
      get :index, {}, valid_session
      assigns(:households).should eq([household])
    end
  end

  describe "GET show" do
    it "assigns the requested household as @household" do
      household = Household.create! valid_attributes
      get :show, {:id => household.to_param}, valid_session
      assigns(:household).should eq(household)
    end
  end

  describe "GET new" do
    it "assigns a new household as @household" do
      get :new, {}, valid_session
      assigns(:household).should be_a_new(Household)
    end
  end

  describe "GET edit" do
    it "assigns the requested household as @household" do
      household = Household.create! valid_attributes
      get :edit, {:id => household.to_param}, valid_session
      assigns(:household).should eq(household)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Household" do
        expect {
          post :create, {:household => valid_attributes}, valid_session
        }.to change(Household, :count).by(1)
      end

      it "assigns a newly created household as @household" do
        post :create, {:household => valid_attributes}, valid_session
        assigns(:household).should be_a(Household)
        assigns(:household).should be_persisted
      end

      it "redirects to the created household" do
        post :create, {:household => valid_attributes}, valid_session
        response.should redirect_to(Household.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved household as @household" do
        # Trigger the behavior that occurs when invalid params are submitted
        Household.any_instance.stub(:save).and_return(false)
        post :create, {:household => {  }}, valid_session
        assigns(:household).should be_a_new(Household)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Household.any_instance.stub(:save).and_return(false)
        post :create, {:household => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested household" do
        household = Household.create! valid_attributes
        # Assuming there are no other households in the database, this
        # specifies that the Household created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Household.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => household.to_param, :household => { "these" => "params" }}, valid_session
      end

      it "assigns the requested household as @household" do
        household = Household.create! valid_attributes
        put :update, {:id => household.to_param, :household => valid_attributes}, valid_session
        assigns(:household).should eq(household)
      end

      it "redirects to the household" do
        household = Household.create! valid_attributes
        put :update, {:id => household.to_param, :household => valid_attributes}, valid_session
        response.should redirect_to(household)
      end
    end

    describe "with invalid params" do
      it "assigns the household as @household" do
        household = Household.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Household.any_instance.stub(:save).and_return(false)
        put :update, {:id => household.to_param, :household => {  }}, valid_session
        assigns(:household).should eq(household)
      end

      it "re-renders the 'edit' template" do
        household = Household.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Household.any_instance.stub(:save).and_return(false)
        put :update, {:id => household.to_param, :household => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested household" do
      household = Household.create! valid_attributes
      expect {
        delete :destroy, {:id => household.to_param}, valid_session
      }.to change(Household, :count).by(-1)
    end

    it "redirects to the households list" do
      household = Household.create! valid_attributes
      delete :destroy, {:id => household.to_param}, valid_session
      response.should redirect_to(households_url)
    end
  end

end
